name: ci/cd

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['test-main']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: check types
        run: npm run type:check

      - name: check format
        run: npm run format:check

      # todo: check lint

      - name: run unit test
        run: npm run test:unit
  cd:
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: login to ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: checkout branch
        uses: actions/checkout@v3

      - name: build and push docker image to ecr
        run: |
          docker build -t ${{ secrets.ECR_SERVER_URI }}:latest .
          docker push ${{ secrets.ECR_SERVER_URI }}:latest